### ISSUE TITLE
BestBuy added new authentication method before checkout

### ISSUE THREAD

**Issue by Kaveman42** [Konyanj0278/BestBuy-Automated-Checkout#7]
Hi Jack,

Does your bot work with the new email/SMS authentication feature BestBuy added during checkout? 

Thanks,
Hovig

**Comment by Konyanj0278** [comment]
Hey Hovig,

It does not at this point I do not see a way to add that feature in without having to create a new bot to monitor emails and sms.

Best Regards, Jack

**Comment by Kaveman42** [comment]
Would your bot allow us to enter that portion manually or does the bot no longer work because of the new changes they made? Thanks for the response by the way.

Sent from my iPhone

On Nov 22, 2020, at 7:32 PM, Jack Konyan <notifications@github.com> wrote:

﻿

Hey Hovig,

It does not at this point I do not see a way to add that feature in without having to create a new bot to monitor emails and sms.

Best Regards, Jack

**Comment by Konyanj0278** [comment]
It could possibly, I would need to see how it works to make it allow for that
